<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="F_IsSpace" Id="{64a3090d-37d8-4578-b255-dbe5dd4579fc}" SpecialFunc="None">
    <Declaration><![CDATA[// Checks if a character is ' '(space) '$t' (horizontal tab) '$n' (newline) '$r' (carriage return) '$f' (form feed) '$v' (vertical tab)
FUNCTION F_IsSpace : BOOL
VAR_INPUT
	t_Char : T_Char;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_IsSpace := 
	(t_Char[0] = 32) OR_ELSE 
	(t_Char[0] = 09) OR_ELSE 
	(t_Char[0] = 10) OR_ELSE 
	(t_Char[0] = 13) OR_ELSE 
	(t_Char[0] = 12) OR_ELSE 
	(t_Char[0] = 11);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>