<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="F_String_Builder" Id="{55e881ac-c530-44b9-b16a-c0ea1631cee2}" SpecialFunc="None">
    <Declaration><![CDATA[// String builder function
FUNCTION F_String_Builder : REFERENCE TO FB_String_Builder
VAR_STAT
	fbString_Builder : FB_String_Builder;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbString_Builder.Clear();
F_String_Builder REF= fbString_Builder;]]></ST>
    </Implementation>
    <LineIds Name="F_String_Builder">
      <LineId Id="7" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>