<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{bb76c191-1e39-4156-925e-1a5af04519cc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_EnumeratorExample();
P_AdapterExample();
P_StringBuilderExample();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="97" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>